name: Notify QA on new QA tasks

on:
  issues:
    types: bug

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: workflows/notification@v1
      with:
        recipients: bug=@psikai
