name: Notify QA on new QA tasks

on:
  issues:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: psikai/grocery-shop
      with:
        recipients: |
          bug=@psikai
